### ISSUE TITLE
Question regarding this plugin

### ISSUE THREAD

**Issue by alainseys** [hairmare/zabbix-icecast#4]
i have followed your turotorial, hen i run your script i get this error, if i copy once the icecast stats to this directory i get the result bu the second time this is empty.

what is the correct usage of this ? 

/tmp/zabbix-icecast-stats.xml:1: parser error : Document is empty

**Comment by zetneteork** [comment]
This issue is related to the permission issue. Make sure the zabbix agent and script are with the same uuid. I've been facing this issue too.

`/etc/zabbix/zabbix_agentd.conf.d/userdata.conf`
```bash 
UserParameter=icecast.global.clients,/usr/local/scripts/zabbix/icestats.sh clients
UserParameter=icecast.global.client_connections,/usr/local/scripts/zabbix/icestats.sh client_connections
UserParameter=icecast.global.sources,/usr/local/scripts/zabbix/icestats.sh sources
UserParameter=icecast.source.listeners[*],/usr/local/scripts/zabbix/icestats.sh mount-listeners $1
UserParameter=icecast.source.slow_listeners[*],/usr/local/scripts/zabbix/icestats.sh mount-slow_listeners $1
```
```bash
/usr/local/scripts/zabbix/icestats.sh
ls -l /usr/local/scripts/zabbix/icestats.sh
-rwxr-xr-x 1 zabbix zabbix 1337 úno 23  2015 /usr/local/scripts/zabbix/icestats.sh
```

My zabbix-agent runs under **zabbix** user

**Comment by alainseys** [comment]
Thanks for the clarification I will test this out

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by catbgmt** [comment]
hellow, i have a problem with script. 
when i start it i got error: warning: failed to load external entity "./xslt/.xsl"
cannot parse ./xslt/.xsl
ls -l icestats.sh
-rwxr-xr-x 1 zabbix zabbix 1337 Jan 31 14:29 icestats.sh

**Comment by hairmare** [comment]
@catbgmt you also need the xslt subdir and it's contents + you need to call the script with an argument (like `./icestats.sh clients` or `./icestats.sh sources`).

I'm going to go ahead and close this issue since the original issue seems to have been solved by setting permissions for the zabbix user.

I'd also like to not that i haven't been using this setup for a while now as it has been replaced with a setup based on this [Icecast Exporter for Prometheus](https://github.com/markuslindenberg/icecast_exporter).
